name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-preview:
    environment: preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.13 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "hy-web-preview" #Must be unique in Heroku
          heroku_email: "info@happyyoga.de"
  build-prod:
    environment: production
    runs-on: ubuntu-latest
    needs: build-preview
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.13 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "hy-web-prod" #Must be unique in Heroku
          heroku_email: "info@happyyoga.de"
